# Generated by Django 4.1.7 on 2024-09-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0019_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='travel_in_Russia.city', verbose_name='город'),
        ),
    ]
